# Generated by Django 4.2.7 on 2023-12-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz_mouhami', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avocat',
            old_name='localisation',
            new_name='nom',
        ),
    ]
